import { keyof } from "zod";

export default async function DashPage() {

const countryFlags = {
  "Afghanistan": { flag: "🇦🇫" }, // Nota: Algunas terminales muestran 🇦🇫
  "Aland Islands": { flag: "🇦🇽" },
  "Albania": { flag: "🇦🇱" },
  "Algeria": { flag: "🇩🇿" },
  "Andorra": { flag: "🇦🇩" },
  "Angola": { flag: "🇦🇴" },
  "Anguilla": { flag: "🇦🇮" },
  "Antarctica": { flag: "🇦🇶" },
  "Antigua And Barbuda": { flag: "🇦🇬" },
  "Argentina": { flag: "🇦🇷" },
  "Armenia": { flag: "🇦🇲" },
  "Aruba": { flag: "🇦🇼" },
  "Australia": { flag: "🇦🇺" },
  "Austria": { flag: "🇦🇹" },
  "Azerbaijan": { flag: "🇦🇿" },
  "Bahamas": { flag: "🇧🇸" },
  "Bahrain": { flag: "🇧🇭" },
  "Bangladesh": { flag: "🇧🇩" },
  "Barbados": { flag: "🇧🇧" },
  "Belarus": { flag: "🇧🇾" },
  "Belgium": { flag: "🇧🇪" },
  "Belize": { flag: "🇧🇿" },
  "Benin": { flag: "🇧🇯" },
  "Bermuda": { flag: "🇧🇲" },
  "Bhutan": { flag: "🇧🇹" },
  "Bolivia": { flag: "🇧🇴" },
  "Bosnia and Herzegovina": { flag: "🇧🇦" },
  "Botswana": { flag: "🇧🇼" },
  "Bouvet Island": { flag: "🇧🇻" },
  "Brazil": { flag: "🇧🇷" },
  "British Indian Ocean Territory": { flag: "🇮🇴" },
  "Brunei": { flag: "🇧🇳" },
  "Bulgaria": { flag: "🇧🇬" },
  "Burkina Faso": { flag: "🇧🇫" },
  "Burundi": { flag: "🇧🇮" },
  "Cambodia": { flag: "🇰🇭" },
  "Cameroon": { flag: "🇨🇲" },
  "Canada": { flag: "🇨🇦" },
  "Cape Verde": { flag: "🇨🇻" },
  "Cayman Islands": { flag: "🇰🇾" },
  "Central African Republic": { flag: "🇨🇫" },
  "Chad": { flag: "🇹🇩" },
  "Chile": { flag: "🇨🇱" },
  "China": { flag: "🇨🇳" },
  "Christmas Island": { flag: "🇨🇽" },
  "Cocos (Keeling) Islands": { flag: "🇨🇨" },
  "Colombia": { flag: "🇨🇴" },
  "Comoros": { flag: "🇰🇲" },
  "Congo": { flag: "🇨🇬" },
  "Cook Islands": { flag: "🇨🇰" },
  "Costa Rica": { flag: "🇨🇷" },
  "Ivory Coast": { flag: "🇨🇮" },
  "Croatia": { flag: "🇭🇷" },
  "Cuba": { flag: "🇨🇺" },
  "Cyprus": { flag: "🇨🇾" },
  "Czech Republic": { flag: "🇨🇿" },
  "Denmark": { flag: "🇩🇰" },
  "Djibouti": { flag: "🇩🇯" },
  "Dominica": { flag: "🇩🇲" },
  "Dominican Republic": { flag: "🇩🇴" },
  "Timor-Leste": { flag: "🇹🇱" },
  "Ecuador": { flag: "🇪🇨" },
  "Egypt": { flag: "🇪🇬" },
  "El Salvador": { flag: "🇸🇻" },
  "Equatorial Guinea": { flag: "🇬🇶" },
  "Eritrea": { flag: "🇪🇷" },
  "Estonia": { flag: "🇪🇪" },
  "Ethiopia": { flag: "🇪🇹" },
  "Falkland Islands": { flag: "🇫🇰" },
  "Faroe Islands": { flag: "🇫🇴" },
  "Fiji Islands": { flag: "🇫🇯" },
  "Finland": { flag: "🇫🇮" },
  "France": { flag: "🇫🇷" },
  "French Polynesia": { flag: "🇵🇫" },
  "French Southern Territories": { flag: "🇹🇫" },
  "Gabon": { flag: "🇬🇦" },
  "Gambia The": { flag: "🇬🇲" },
  "Georgia": { flag: "🇬🇪" },
  "Germany": { flag: "🇩🇪" },
  "Ghana": { flag: "🇬🇭" },
  "Gibraltar": { flag: "🇬🇮" },
  "Greece": { flag: "🇬🇷" },
  "Greenland": { flag: "🇬🇱" },
  "Grenada": { flag: "🇬🇩" },
  "Guadeloupe": { flag: "🇬🇵" },
  "Guam": { flag: "🇬🇺" },
  "Guatemala": { flag: "🇬🇹" },
  "Guernsey": { flag: "🇬🇬" },
  "Guinea": { flag: "🇬🇳" },
  "Guinea-Bissau": { flag: "🇬🇼" },
  "Guyana": { flag: "🇬🇾" },
  "Haiti": { flag: "🇭🇹" },
  "Heard Island and McDonald Islands": { flag: "🇭🇲" },
  "Honduras": { flag: "🇭🇳" },
  "Hong Kong S.A.R.": { flag: "🇭🇰" },
  "Hungary": { flag: "🇭🇺" },
  "Iceland": { flag: "🇮🇸" },
  "India": { flag: "🇮🇳" },
  "Indonesia": { flag: "🇮🇩" },
  "Iran": { flag: "🇮🇷" },
  "Iraq": { flag: "🇮🇶" },
  "Ireland": { flag: "🇮🇪" },
  "Israel": { flag: "🇮🇱" },
  "Italy": { flag: "🇮🇹" },
  "Jamaica": { flag: "🇯🇲" },
  "Japan": { flag: "🇯🇵" },
  "Jersey": { flag: "🇯🇪" },
  "Jordan": { flag: "🇯🇴" },
  "Kazakhstan": { flag: "🇰🇿" },
  "Kenya": { flag: "🇰🇪" },
  "Kiribati": { flag: "🇰🇮" },
  "North Korea": { flag: "🇰🇵" },
  "South Korea": { flag: "🇰🇷" },
  "Kosovo": { flag: "🇽🇰" },
  "Kuwait": { flag: "🇰🇼" },
  "Kyrgyzstan": { flag: "🇰🇬" },
  "Laos": { flag: "🇱🇦" },
  "Latvia": { flag: "🇱🇻" },
  "Lebanon": { flag: "🇱🇧" },
  "Lesotho": { flag: "🇱🇸" },
  "Liberia": { flag: "🇱🇷" },
  "Libya": { flag: "🇱🇾" },
  "Liechtenstein": { flag: "🇱🇮" },
  "Lithuania": { flag: "🇱🇹" },
  "Luxembourg": { flag: "🇱🇺" },
  "Macau S.A.R.": { flag: "🇲🇴" },
  "Macedonia": { flag: "🇲🇰" },
  "Madagascar": { flag: "🇲🇬" },
  "Malawi": { flag: "🇲🇼" },
  "Malaysia": { flag: "🇲🇾" },
  "Maldives": { flag: "🇲🇻" },
  "Mali": { flag: "🇲🇱" },
  "Malta": { flag: "🇲🇹" },
  "Man (Isle of)": { flag: "🇮🇲" },
  "Marshall Islands": { flag: "🇲🇭" },
  "Martinique": { flag: "🇲🇶" },
  "Mauritania": { flag: "🇲🇷" },
  "Mauritius": { flag: "🇲🇺" },
  "Mayotte": { flag: "🇾🇹" },
  "Mexico": { flag: "🇲🇽" },
  "Micronesia": { flag: "🇫🇲" },
  "Moldova": { flag: "🇲🇩" },
  "Monaco": { flag: "🇲🇨" },
  "Mongolia": { flag: "🇲🇳" },
  "Montenegro": { flag: "🇲🇪" },
  "Montserrat": { flag: "🇲🇸" },
  "Morocco": { flag: "🇲🇦" },
  "Mozambique": { flag: "🇲🇿" },
  "Myanmar": { flag: "🇲🇲" },
  "Namibia": { flag: "🇳🇦" },
  "Nauru": { flag: "🇳🇷" },
  "Nepal": { flag: "🇳🇵" },
  "Netherlands": { flag: "🇳🇱" },
  "New Caledonia": { flag: "🇳🇨" },
  "New Zealand": { flag: "🇳🇿" },
  "Nicaragua": { flag: "🇳🇮" },
  "Niger": { flag: "🇳🇪" },
  "Nigeria": { flag: "🇳🇬" },
  "Niue": { flag: "🇳🇺" },
  "Norfolk Island": { flag: "🇳🇫" },
  "Northern Mariana Islands": { flag: "🇲🇵" },
  "Norway": { flag: "🇳🇴" },
  "Oman": { flag: "🇴🇲" },
  "Pakistan": { flag: "🇵🇰" },
  "Palau": { flag: "🇵🇼" },
  "Palestinian Territory Occupied": { flag: "🇵🇸" },
  "Panama": { flag: "🇵🇦" },
  "Papua new Guinea": { flag: "🇵🇬" },
  "Paraguay": { flag: "🇵🇾" },
  "Peru": { flag: "🇵🇪" },
  "Philippines": { flag: "🇵🇭" },
  "Pitcairn Island": { flag: "🇵🇳" },
  "Poland": { flag: "🇵🇱" },
  "Portugal": { flag: "🇵🇹" },
  "Puerto Rico": { flag: "🇵🇷" },
  "Qatar": { flag: "🇶🇦" },
  "Réunion": { flag: "🇷🇪" },
  "Romania": { flag: "🇷🇴" },
  "Russia": { flag: "🇷🇺" },
  "Rwanda": { flag: "🇷🇼" },
  "Saint Helena": { flag: "🇸🇭" },
  "Saint Kitts And Nevis": { flag: "🇰🇳" },
  "Saint Lucia": { flag: "🇱🇨" },
  "Saint Pierre and Miquelon": { flag: "🇵🇲" },
  "Saint Vincent And The Grenadines": { flag: "🇻🇨" },
  "Saint-Barthelemy": { flag: "🇧🇱" },
  "Saint-Martin (French part)": { flag: "🇲🇫" },
  "Samoa": { flag: "🇼🇸" },
  "San Marino": { flag: "🇸🇲" },
  "Sao Tome and Principe": { flag: "🇸🇹" },
  "Saudi Arabia": { flag: "🇸🇦" },
  "Senegal": { flag: "🇸🇳" },
  "Serbia": { flag: "🇷🇸" },
  "Seychelles": { flag: "🇸🇨" },
  "Sierra Leone": { flag: "🇸🇱" },
  "Singapore": { flag: "🇸🇬" },
  "Slovakia": { flag: "🇸🇰" },
  "Slovenia": { flag: "🇸🇮" },
  "Solomon Islands": { flag: "🇸🇧" },
  "Somalia": { flag: "🇸🇴" },
  "South Africa": { flag: "🇿🇦" },
  "South Georgia and the South Sandwich Islands": { flag: "🇬🇸" },
  "South Sudan": { flag: "🇸🇸" },
  "Spain": { flag: "🇪🇸" },
  "Sri Lanka": { flag: "🇱🇰" },
  "Sudan": { flag: "🇸🇩" },
  "Suriname": { flag: "🇸🇷" },
  "Svalbard And Jan Mayen Islands": { flag: "🇸🇯" },
  "Swaziland": { flag: "🇸🇿" },
  "Sweden": { flag: "🇸🇪" },
  "Switzerland": { flag: "🇨🇭" },
  "Syria": { flag: "🇸🇾" },
  "Taiwan": { flag: "🇹🇼" },
  "Tajikistan": { flag: "🇹🇯" },
  "Tanzania": { flag: "🇹🇿" },
  "Thailand": { flag: "🇹🇭" },
  "Togo": { flag: "🇹🇬" },
  "Tokelau": { flag: "🇹🇰" },
  "Tonga": { flag: "🇹🇴" },
  "Trinidad And Tobago": { flag: "🇹🇹" },
  "Tunisia": { flag: "🇹🇳" },
  "Turkey": { flag: "🇹🇷" },
  "Turkmenistan": { flag: "🇹🇲" },
  "Turks And Caicos Islands": { flag: "🇹🇨" },
  "Tuvalu": { flag: "🇹🇻" },
  "Uganda": { flag: "🇺🇬" },
  "Ukraine": { flag: "🇺🇦" },
  "United Arab Emirates": { flag: "🇦🇪" },
  "United Kingdom": { flag: "🇬🇧" },
  "United States": { flag: "🇺🇸" },
  "United States Minor Outlying Islands": { flag: "🇺🇲" },
  "Uruguay": { flag: "🇺🇾" },
  "Uzbekistan": { flag: "🇺🇿" },
  "Vanuatu": { flag: "🇻🇺" },
  "Vatican City State (Holy See)": { flag: "🇻🇦" },
  "Venezuela": { flag: "🇻🇪" },
  "Vietnam": { flag: "🇻🇳" },
  "Virgin Islands (British)": { flag: "🇻🇬" },
  "Virgin Islands (US)": { flag: "🇻🇮" },
  "Wallis And Futuna": { flag: "🇼🇫" },
  "Western Sahara": { flag: "🇪🇭" },
  "Yemen": { flag: "🇾🇪" },
  "Zambia": { flag: "🇿🇲" },
  "Zimbabwe": { flag: "🇿🇼" }
};
  
  return (
    <div className="w-full h-full bg-white flex justify-start  gap-2 items-center grow">

      {
        //@ts-ignore
        // Object.keys(countryFlags).map( el => <p className={"key_"+el}> {el} = {countryFlags[el].flag}</p>)
      }
      {/* <div className="w-full bg-bg-sidebar h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">bg-sidebar</p></div>
      <div className="w-full bg-back-1 h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">back-1</p></div>
      <div className="w-full bg-done-button-bg h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">done-button-bg</p></div>
      <div className="w-full bg-border-sidebar h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">border-sidebar</p></div>
      <div className="w-full bg-back-header h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">back-header</p></div>
      <div className="w-full bg-hover-back-1 h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">hover-back-1</p></div>
      <div className="w-full bg-gray-10 h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">gray-10</p></div>
      <div className="w-full bg-done-button-text h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">done-button-text</p></div>
      <div className="w-full bg-no-money h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">no-money</p></div>
      <div className="w-full bg-title-table h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">title-table</p></div>
      <div className="w-full bg-sub-title h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">sub-title</p></div>
      <div className="w-full bg-body h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">body</p></div>
      <div className="w-full bg-title h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">title</p></div>
      <div className="w-full bg-primary-bg h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">primary-bg</p></div>
      <div className="w-full bg-primary-bg-2 h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">primary-bg-2</p></div>
      <div className="w-full bg-details h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">details</p></div>
      <div className="w-full bg-primary h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">primary</p></div>
      <div className="w-full bg-danger h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">danger</p></div>
      <div className="w-full bg-out-client h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">out-client</p></div>
      <div className="w-full bg-in-client h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">in-client</p></div>
      <div className="w-full bg-green-app h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">green-app</p></div>
      <div className="w-full bg-money h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">money</p></div>
      <div className="w-full bg-stars h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">stars</p></div>
      <div className="w-full bg-orange-1 h-20 flex items-center"><p className="text-xl text-center font-bold mx-auto ">orange-1</p></div> */}
      
    </div>
  );
}


/**
 * Afganistan
 * Netherlands Antilles
 */